---
- name: Create users with home directory
  user: 
    name: {{ username }}
    shell: /bin/bash 
    createhome: yes 
    comment: 'Created by Ansible'
    password: 'Colombia123'
    state: present

