---
- name: Create users with home directory
  user: 
    name: {{ item.username }} 
    shell: /bin/bash 
    createhome: yes 
    comment: 'Created by Ansible'
    password: 'Colombia123'
    state: present
  with_items: 
    - {{ users }}
