---
- name: Create users with home directory
  user: 
    name: "{{ item.username }}"
    shell: /bin/bash 
    createhome: yes 
    password: "{{ item.password }}"
    comment: 'Created by Ansible'
    state: present
    groups:
      - "{{ item.group }}"
    update_password: on_create
  with_items: 
    - "{{ users }}"
