---
- name: "Memoria Fisica y CPU"
  shell: free | grep -i mem | awk '{print ($4*100)/$2}'
  register: memory_porcent_free
  
- name: "Memoria Fisica y CPU"
  shell: sar -u 1 1 | sed -n 4p | awk '{print $9}'
  register: cpu_porcent_free

- name: "Memoria Fisica y CPU"
  shell:  free | grep -i swap | awk '{print ($3*100)/$2}'
  register: memory_swap_porcent

- name: "Creacion Vista Media HTML"
  template: src=Host.j2.html dest=/tmp/{{ ansible_hostname }}.html
  delegate_to: localhost

- name: "Creacion JS"
  template: src=dateComplete.j2.js dest=/tmp/date{{ ansible_hostname }}.js
  delegate_to: localhost