---
- name: Verificando...
  raw: ((Get-Host).CurrentUICulture).name
  register: Languaje

- debug: msg={{ Languaje.stdout }}

- name: Creacion Carpeta - HTML
  file:
      path: /opt/Tomcat9/webapps/checkWin
      state: directory
      mode: '777'
  delegate_to: localhost
  run_once: true

- name: 
  shell: date | awk '{print $3 $4 $NF}'
  register: Fecha
  delegate_to: localhost
  run_once: yes

- name: Creacion Carpeta 
  file:
      path: /opt/Tomcat9/webapps/checkWin/Check_{{ Fecha.stdout }}
      state: directory
      mode: '777'
  delegate_to: localhost

- name: Verificando Lenguaje ...
  include: Win_ES.yml
  when: Languaje.stdout == "en-ES\r\n"

- name: Verificando Lenguaje ...
  include: Win_US.yml
  when: Languaje.stdout == "en-US\r\n"

- include: Union.yml

- debug: msg='Por Favor ingresar a la URL:http://172.22.16.179:443/checkWin/Check_{{ Fecha.stdout }} Para poder validar la captura de los 7 Pasos de las Maquinas'
  run_once: yes
  
- debug: msg='Creado por:Juan Jose Quintero R.'
  run_once: yes
