---
- name: Verificando...
  raw: ((Get-Host).CurrentUICulture).name
  register: Languaje

- name: Creacion Carpeta - HTML
  file:
      path: /opt/Tomcat9/webapps/checkWin
      state: directory
      mode: '777'
  delegate_to: localhost
  run_once: true

- name: Creacion Carpeta 
  file:
      path: /opt/Tomcat9/webapps/checkWin/{{ ansible_hostname }}
      state: directory
      mode: '777'
  delegate_to: localhost

- name: Verificando Lenguaje ...
  include: Win_ES.yml
  when: Languaje.stdout_lines == "es-ES"

- name: Verificando Lenguaje ...
  include: Win_US.yml
  when: Languaje.stdout_lines == "es-US"

- debug: msg={{ Languaje.stdout_lines }}
