---
- name: Verificando...
  raw: ((Get-Host).CurrentUICulture).name
  register: Languaje

- name: Lenguaje
  debug: msg='Espanol'
  when: Languaje.stdout == "es-ES\r\n"


- name: Creacion Carpeta - HTML
  file:
      path: /opt/Tomcat9/webapps/checkWin
      state: directory
      mode: '777'
  delegate_to: localhost
  run_once: true

- name: Creacion Carpeta 
  file:
      path: /opt/Tomcat9/webapps/checkWin/{{ ansible_hostname }}
      state: directory
      mode: '777'
  delegate_to: localhost

- name: Verificando Lenguaje ...
  include: Win_ES.yml
  when: Languaje.stdout == "es-ES\r\n"

- name: Verificando Lenguaje ...
  include: Win_US.yml
  when: Languaje.stdout == "es-US\r\n"

- debug: msg={{ Languaje.stdout }}
