---
- name: Realizando Cambio - Logrotate (Template)
  template:
      dest: /etc/logrotate.d/syslog
      src: new_syslog.j2
      owner: root 
      group: root 
      mode: '0644'
      backup: yes 

- name: Aplicando Cambio - Comando
  shell: sudo /usr/sbin/logrotate -f /etc/logrotate.d/syslog
  become: yes
  become_user: root

- debug:
    msg: Proceso Finalizado ...
