---
- name: Create users with home directory
  win_user: 
    name: "{{ item.username }}"
    fullname: "{{ item.username }}"
    description: "Usuario Creado Bajo el Caso - {{ item.case }}"
    password: "{{ item.password }}"
    state: present
  with_items: 
    - "{{ users }}"
