---
- name: Create users with home directory
  win_user: 
    name: "{{ item.username }}"
    fullname: "{{ item.username }}"
    description: "Usuario de Pruebas - Ansible"
    password: 'Colombia123'
    state: present
  with_items: 
    - "{{ users }}"
